
apiVersion: v1
kind: Service
metadata:
  name: truck-demo-ui-svc
spec:
  type: LoadBalancer
  selector:
    app: truck-demo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: truck-demo-ui
  name: truck-demo-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: truck-demo-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: truck-demo-ui
    spec:
      containers:
      - image: d2iqdemo/truck-demo-ui:arm
        imagePullPolicy: Always
        name: truck-demo-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CURRENT_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENV_API_URL
          valueFrom:
            configMapKeyRef:
              name: dataservices
              key: API
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
  name: truck-demo-ui
spec:
  rules:
  - http:
      paths:
      - path: /demo-ui
        pathType: Prefix
        backend:
          service:
            name: truck-demo-ui-svc
            port: 
              number: 80